---
- name: Configure PDUs
  hosts: opengear
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Configure a PDU accessed via SNMP
      opengear.ng.pdu_config:
        config:
          - name: rack-pdu-01
            driver:
              id: apc24
            method: snmp
            monitor: true
            snmp:
              address: 192.168.1.50
              version: '2c'
              community: public
              port: 161
        state: merged

    - name: Name and map outlets on the PDU
      opengear.ng.pdu_config:
        config:
          - name: rack-pdu-01
            outlets:
              - number: 1
                name: web-server-1
              - number: 2
                name: web-server-2
        state: merged

    - name: Gather PDU configuration
      opengear.ng.facts:
        gather_network_resources:
          - pdu_config
