#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_physifs module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class PhysifsArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_physifs module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'bond_setting': {'options': {'mode': {'type': 'str'},
                                                                         'poll_interval': {'type': 'int'},
                                                                         'primary_slave': {'type': 'str'}},
                                                             'type': 'dict'},
                                            'bridge_setting': {'options': {'primary_slave': {'type': 'str'},
                                                                           'stp_enabled': {'type': 'bool'}},
                                                               'type': 'dict'},
                                            'cellular_setting': {'options': {'active_sim': {'type': 'int'},
                                                                             'id': {'type': 'str'},
                                                                             'sim_failback_disconnect_mode': {
                                                                                 'type': 'str'},
                                                                             'sim_failback_policy': {'type': 'str'},
                                                                             'sim_failover_disconnect_mode': {
                                                                                 'type': 'str'},
                                                                             'sim_failover_policy': {'type': 'str'},
                                                                             'sims': {'elements': 'dict',
                                                                                      'options': {
                                                                                          'apn': {'type': 'str'},
                                                                                          'fail_probe_address': {
                                                                                              'type': 'str'},
                                                                                          'fail_probe_count': {
                                                                                              'type': 'int'},
                                                                                          'fail_probe_interval': {
                                                                                              'type': 'int'},
                                                                                          'fail_probe_threshold': {
                                                                                              'type': 'int'},
                                                                                          'failback_delay': {
                                                                                              'type': 'int'},
                                                                                          'id': {'type': 'str'},
                                                                                          'iptype': {'type': 'str'},
                                                                                          'password': {'type': 'str'},
                                                                                          'slot': {'type': 'int'},
                                                                                          'username': {'type': 'str'}},
                                                                                      'type': 'list'}},
                                                                 'type': 'dict'},
                                            'description': {'type': 'str'},
                                            'enabled': {'type': 'bool'},
                                            'ethernet_setting': {'options': {'link_speed': {'type': 'str'}},
                                                                 'type': 'dict'},
                                            'id': {'type': 'str'},
                                            'media': {'type': 'str'},
                                            'mtu': {'type': 'int'},
                                            'name': {'type': 'str'},
                                            'slaves': {'elements': 'str', 'type': 'list'},
                                            'vlan_setting': {'options': {'parent_physif': {'type': 'str'},
                                                                         'vlan_id': {'type': 'int'}},
                                                             'type': 'dict'}},
                                'type': 'list'},
                     'state': {'choices': ['merged',
                                           'replaced',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
