#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_ports module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class PortsArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_ports module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'auto_discover': {'options': {'ports': {'elements': 'int',
                                                                                    'type': 'list'},
                                                                          'schedule': {'options': {
                                                                              'day_of_month': {'type': 'int'},
                                                                              'day_of_week': {'type': 'int'},
                                                                              'enabled': {'type': 'bool'},
                                                                              'hour': {'type': 'int'},
                                                                              'minute': {'type': 'int'},
                                                                              'period': {'type': 'str'}},
                                                                              'type': 'dict'},
                                                                          'start': {'type': 'bool'}},
                                                              'type': 'dict'},
                                            'ports': {'elements': 'dict',
                                                      'options': {'baudrate': {'type': 'str'},
                                                                  'available_baudrates': {'type': 'str'},
                                                                  'databits': {'type': 'str'},
                                                                  'escape_char': {'type': 'str'},
                                                                  'id': {'type': 'str'},
                                                                  'ip_alias': {'elements': 'dict',
                                                                               'options': {'interface': {'type': 'str'},
                                                                                           'ipaddress': {
                                                                                               'type': 'str'}},
                                                                               'type': 'list'},
                                                                  'kernel_debug': {'type': 'bool'},
                                                                  'label': {'type': 'str'},
                                                                  'logging_level': {'type': 'str'},
                                                                  'mode': {'type': 'str'},
                                                                  'name': {'type': 'str'},
                                                                  'parity': {'type': 'str'},
                                                                  'pinout': {'type': 'str'},
                                                                  'portnum': {'type': 'str'},
                                                                  'power': {'type': 'str'},
                                                                  'sessions': {'elements': 'dict',
                                                                               'options': {
                                                                                   'client_pid': {'type': 'int'},
                                                                                   'username': {'type': 'str'}},
                                                                               'type': 'list'},
                                                                  'stopbits': {'type': 'str'},
                                                                  'terminal_emulation': {'type': 'str'},
                                                                  'single_session': {'type': 'bool'},
                                                                  'raw_tcp': {'type': 'bool'}},
                                                      'type': 'list'}},
                                'type': 'dict'},
                     'state': {'choices': ['merged',
                                           'replaced',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301