#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_services module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class ServicesArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_services module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'https': {'options': {'cert': {'type': 'str'},
                                                                  'csr': {
                                                                      'options': {'challenge_password': {'type': 'str'},
                                                                                  'common_name': {'type': 'str'},
                                                                                  'country': {'type': 'str'},
                                                                                  'csr': {'type': 'str'},
                                                                                  'email': {'type': 'str'},
                                                                                  'key_length': {'type': 'str'},
                                                                                  'locality': {'type': 'str'},
                                                                                  'org_unit': {'type': 'str'},
                                                                                  'organization': {'type': 'str'},
                                                                                  'private_key': {'type': 'string'},
                                                                                  'state': {'type': 'str'}},
                                                                      'type': 'dict'}},
                                                      'type': 'dict'},
                                            'lldp': {'options': {'description': {'type': 'str'},
                                                                 'enabled': {'type': 'bool'},
                                                                 'physifs': {'type': 'str'},
                                                                 'platform': {'type': 'str'}},
                                                     'type': 'dict'},
                                            'ntp': {'options': {'enabled': {'type': 'bool'},
                                                                'servers': {'options': {'value': {'type': 'str'}},
                                                                            'type': 'list'}},
                                                    'type': 'dict'},
                                            'routing': {'options': {'bgpd': {'options': {'enabled': {'type': 'bool'}},
                                                                             'type': 'dict'},
                                                                    'isisd': {'options': {'enabled': {'type': 'bool'}},
                                                                              'type': 'dict'},
                                                                    'ospfd': {'options': {'enabled': {'type': 'bool'}},
                                                                              'type': 'dict'},
                                                                    'ripd': {'options': {'enabled': {'type': 'bool'}},
                                                                             'type': 'dict'}},
                                                        'type': 'dict'},
                                            'snmp_alert_managers': {'elements': 'dict',
                                                                    'options': {'address': {'type': 'str'},
                                                                                'auth_password': {'type': 'str'},
                                                                                'auth_protocol': {'type': 'str'},
                                                                                'community': {'type': 'str'},
                                                                                'engine_id': {'type': 'str'},
                                                                                'id': {'type': 'str'},
                                                                                'msg_type': {'type': 'str'},
                                                                                'multi_field_identifer': {
                                                                                    'type': 'str'},
                                                                                'name': {'type': 'str'},
                                                                                'port': {'type': 'int'},
                                                                                'privacy_password': {'type': 'str'},
                                                                                'privacy_protocol': {'type': 'str'},
                                                                                'protocol': {'type': 'str'},
                                                                                'security_level': {'type': 'str'},
                                                                                'username': {'type': 'str'},
                                                                                'version': {'type': 'str'}},
                                                                    'type': 'list'},
                                            'snmp_manager': {'options': {'address': {'type': 'str'},
                                                                         'auth_password': {'type': 'str'},
                                                                         'auth_protocol': {'type': 'str'},
                                                                         'community': {'type': 'str'},
                                                                         'engine_id': {'type': 'str'},
                                                                         'msg_type': {'type': 'str'},
                                                                         'port': {'type': 'int'},
                                                                         'privacy_password': {'type': 'str'},
                                                                         'privacy_protocol': {'type': 'str'},
                                                                         'protocol': {'type': 'str'},
                                                                         'security_level': {'type': 'str'},
                                                                         'username': {'type': 'str'},
                                                                         'version': {'type': 'str'}},
                                                             'type': 'dict'},
                                            'snmpd': {'options': {'auth_localized_key': {'type': 'str'},
                                                                  'auth_password': {'type': 'str'},
                                                                  'auth_protocol': {'type': 'str'},
                                                                  'auth_use_plaintext': {'type': 'bool'},
                                                                  'enable_legacy_versions': {'type': 'bool'},
                                                                  'enable_secure_snmp': {'type': 'bool'},
                                                                  'enabled': {'type': 'bool'},
                                                                  'engine_id': {'type': 'str'},
                                                                  'port': {'type': 'int'},
                                                                  'priv_localized_key': {'type': 'str'},
                                                                  'priv_password': {'type': 'str'},
                                                                  'priv_protocol': {'type': 'str'},
                                                                  'priv_use_plaintext': {'type': 'bool'},
                                                                  'protocol': {'type': 'str'},
                                                                  'rocommunity': {'type': 'str'},
                                                                  'rwcommunity': {'type': 'str'},
                                                                  'security_level': {'type': 'str'},
                                                                  'security_name': {'type': 'str'}},
                                                      'type': 'dict'},
                                            'ssh': {'options': {'maxstartups_full': {'type': 'int'},
                                                                'maxstartups_start': {'type': 'int'},
                                                                'min_startups_rate': {'type': 'int'},
                                                                'ssh_url_delimiter': {'type': 'str'},
                                                                'unauthenticated_serial_port_access': {'type': 'bool'}},
                                                    'type': 'dict'},
                                            'syslog': {'elements': 'dict',
                                                       'options': {'address': {'type': 'str'},
                                                                   'description': {'type': 'str'},
                                                                   'id': {'type': 'str'},
                                                                   'min_severity': {'type': 'str'},
                                                                   'port': {'type': 'int'},
                                                                   'port_logging_enabled': {'type': 'bool'},
                                                                   'protocol': {'type': 'str'}},
                                                       'type': 'list'}},
                                'type': 'dict'},
                     'state': {'choices': ['merged',
                                           'replaced',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
