#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_system module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class SystemArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_system module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'admin_info': {'options': {'contact': {'type': 'str'},
                                                                       'hostname': {'type': 'str'},
                                                                       'location': {'type': 'str'}},
                                                           'type': 'dict'},
                                            'banner': {'type': 'str'},
                                            'cell_reliability_test': {'options': {'enabled': {'type': 'bool'},
                                                                                  'period': {'type': 'int'},
                                                                                  'signal_strength_threshold': {
                                                                                      'options': {
                                                                                          'lower': {'type': 'int'},
                                                                                          'upper': {'type': 'int'}},
                                                                                      'type': 'dict'},
                                                                                  'test_url': {'elements': 'str',
                                                                                               'type': 'list'}},
                                                                      'type': 'dict'},
                                            'cli_session_timeout': {'type': 'int'},
                                            'hostname': {'type': 'str'},
                                            'reboot': {'type': 'bool'},
                                            'ssh_port': {'type': 'int'},
                                            'system_authorized_keys': {'elements': 'dict',
                                                                       'options': {'id': {'type': 'str'},
                                                                                   'key': {'type': 'str'},
                                                                                   'username': {'type': 'str'},
                                                                                   'multi_field_identifier': {'type': 'str'}},
                                                                       'type': 'list'},
                                            'time': {'type': 'str'},
                                            'timezone': {'type': 'str'},
                                            'webui_session_timeout': {'type': 'int'}},
                                'type': 'dict'},
                     'state': {'choices': ['merged',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
