#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_pdu module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class PduArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_pdu module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'driver': {'type': 'str'},
                                            'id': {'type': 'str'},
                                            'method': {'type': 'str'},
                                            'monitor': {'type': 'bool'},
                                            'name': {'type': 'str'},
                                            'powerman': {'options': {'id': {'type': 'str'},
                                                                     'password': {'type': 'str'},
                                                                     'port': {'type': 'str'},
                                                                     'username': {'type': 'str'}},
                                                         'type': 'dict'},
                                            'shell': {'options': {'id': {'type': 'str'},
                                                                  'passsword': {'type': 'str'},
                                                                  'port': {'type': 'str'},
                                                                  'username': {'type': 'str'}},
                                                      'type': 'dict'},
                                            'snmp': {'options': {'address': {'type': 'str'},
                                                                 'auth_password': {'type': 'str'},
                                                                 'auth_protocol': {'type': 'str'},
                                                                 'community': {'type': 'str'},
                                                                 'engine_id': {'type': 'str'},
                                                                 'id': {'type': 'str'},
                                                                 'port': {'type': 'int'},
                                                                 'privacy_password': {'type': 'str'},
                                                                 'privacy_protocol': {'type': 'str'},
                                                                 'protocol': {'type': 'str'},
                                                                 'security_level': {'type': 'str'},
                                                                 'username': {'type': 'str'},
                                                                 'version': {'type': 'str'}},
                                                     'type': 'dict'}},
                                'type': 'list'},
                     'state': {'choices': ['merged',
                                           'replaced',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
