---

- name: Configure services
  hosts: all
  connection: httpapi
  tasks:
    - name: Add Google NTP server
      opengear.om.om_services:
        config:
          ntp:
            enabled: true
            servers:
              - value: au.pool.ntp.org
        state:
          replaced
