---

- name: System configuration
  hosts: all
  connection: httpapi
  tasks:
    - name: Change Admin Infro
      opengear.om.om_system:
        config:
          admin_info:
            hostname: om1000
            contact: avankatw@digi.com.au
            location: AUS
    - name: Change Timezone
      opengear.om.om_system:
        config:
          timezone: Australia/Brisbane
    - name: Add SSH Keys
      opengear.om.om_system:
        config:
          system_authorized_keys:
            - key: "{{ 'rsa key' }}"
              username: root
              id: users_ssh_authorized_keys-1
        state:
          deleted
