---

- name: User configuration
  hosts: all
  connection: httpapi
  gather_facts: true
  tasks:
    - name: Add user
      opengear.om.om_users:
        config:
          - username: test1
            enabled: false
            no_password: true
            description: This user was changed.
          - username: test3
            enabled: true
            no_password: true
            description: This user was added.
        state:
          overridden
