#
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the om_users module
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


class UsersArgs(object):  # pylint: disable=R0903
    """The arg spec for the om_users module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'description': {'type': 'str'},
                                            'enabled': {'type': 'bool'},
                                            'groups': {'elements': 'str', 'type': 'list'},
                                            'hashed_password': {'type': 'str'},
                                            'id': {'type': 'str'},
                                            'no_password': {'type': 'bool'},
                                            'password': {'type': 'str'},
                                            'ssh_password_enabled': {'type': 'bool'},
                                            'username': {'type': 'str'}},
                                'type': 'list'},
                     'state': {'choices': ['merged',
                                           'replaced',
                                           'overridden',
                                           'deleted',
                                           'gathered',
                                           'rendered'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
