#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################


from __future__ import absolute_import, division, print_function
__metaclass__ = type


ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_groups
version_added: 1.0.0
short_description: Manages user attributes of opengear om groups
description: 
  - Manages user attributes of opengear om groups
author: 
  - "Adrian Van Katwyk (@avankatwyk)"
  - "Matt Witmer (@mattwit)"
options:
  config:
    description: Retrieve and update user information
    type: list
    elements: dict
    suboptions:
      id:
        type: str
        description: group id
      groupname:
        type: str
        description: group name
      enabled:
        type: bool
        description: group enabled or disabled
      mode:
        type: str
        description: group mode
      role:
        type: str
        description: group role
      description:
        type: str
        description: group description
      ports:
        type: list
        description: ports assigned to group
        elements: str
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
 
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.groups.groups import GroupsArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.groups.groups import Groups


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=GroupsArgs.argument_spec,
                           supports_check_mode=True)

    result = Groups(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
