#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for om_physifs
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_physifs
version_added: 1.0.0
short_description: 'Manages physif attributes of om physifs'
description: 'Manages physif attributes of om physifs.'
author: Adrian Van Katwyk
options:
  config:
    description: Configuring and viewing physifs information
    type: list
    elements: dict
    suboptions:
      enabled:
        type: bool
      name:
        type: str
      id:
        type: str
      mtu:
        type: int
      description:
        type: str
      media:
        type: str
      slaves:
        type: list
        elements: str
      bond_setting:
        type: dict
        suboptions:
          mode:
            type: str
          poll_interval:
            type: int
          primary_slave:
            type: str
      bridge_setting:
        type: dict
        suboptions:
          stp_enabled:
            type: bool
          primary_slave:
            type: str
      vlan_setting:
        type: dict
        suboptions:
          parent_physif:
            type: str
          vlan_id:
            type: int
      cellular_setting:
        type: dict
        suboptions:
          id:
            type: str
          active_sim:
            type: int
          sim_failover_policy:
            type: str
          sim_failover_disconnect_mode:
            type: str
          sim_failback_policy:
            type: str
          sim_failback_disconnect_mode:
            type: str
          sims:
            type: list
            elements: dict
            suboptions:
              id:
                type: str
              slot:
                type: int
              apn:
                type: str
              username:
                type: str
              password:
                type: str
              iptype:
                type: str
              failback_delay:
                type: int
              fail_probe_address:
                type: str
              fail_probe_interval:
                type: int
              fail_probe_count:
                type: int
              fail_probe_threshold:
                type: int
      ethernet_setting:
        type: dict
        suboptions:
          link_speed:
            type: str
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""
EXAMPLES = """
# Using deleted

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  myos_interfaces:
    operation: deleted

<placeholder for the configuration example after module invocation>


# Using merged

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  nxos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: merged

<placeholder for the configuration example after module invocation>


# Using overridden

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  myos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: overridden

<placeholder for the configuration example after module invocation>


# Using replaced

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  nxos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: replaced

<placeholder for the configuration example after module invocation>


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.physifs.physifs import PhysifsArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.physifs.physifs import Physifs


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=PhysifsArgs.argument_spec,
                           supports_check_mode=True)

    result = Physifs(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
