#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for om_physifs
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_physifs
version_added: 1.0.0
short_description: Manages physif attributes of om physifs
description:
  - Manages physif attributes of om physifs
author:
  - "Adrian Van Katwyk (@avankatwyk)"
  - "Matt Witmer (@mattwit)"
options:
  config:
    description: Configuring and viewing physical interface information
    type: list
    elements: dict
    suboptions:
      enabled:
        type: bool
        description: enabled or disabled
      name:
        type: str
        description: interface name
      id:
        type: str
        description: id
      mtu:
        type: int
        description: mtu size
      description:
        type: str
        description: interface description
      media:
        type: str
        description: media type
      slaves:
        type: list
        description: slave interfaces
        elements: str
      bond_setting:
        type: dict
        description: bond configuration
        suboptions:
          mode:
            type: str
            description: bond mode
          poll_interval:
            type: int
            description: poll interval
          primary_slave:
            type: str
            description: primary slave interface
      bridge_setting:
        type: dict
        description: bridge configuration
        suboptions:
          stp_enabled:
            type: bool
            description: stp enabled or disabled on bridge
          primary_slave:
            type: str
            description: primary slave interface on bridge
      vlan_setting:
        type: dict
        description: vlan configuration
        suboptions:
          parent_physif:
            type: str
            description: parent interface
          vlan_id:
            type: int
            description: vlan id
      cellular_setting:
        type: dict
        description: cellular configuration
        suboptions:
          id:
            type: str
            description: id
          active_sim:
            type: int
            description: active sim
          sim_failover_policy:
            type: str
            description: sim failover policy
          sim_failover_disconnect_mode:
            type: str
            description: sim failover disconnect mode
          sim_failback_policy:
            type: str
            description: sim failback policy
          sim_failback_disconnect_mode:
            type: str
            description: sim failback disconnect mode
          sims:
            type: list
            description: sim
            elements: dict
            suboptions:
              id:
                type: str
                description: id
              slot:
                type: int
                description: slot
              apn:
                type: str
                description: apn
              username:
                type: str
                description: username
              password:
                type: str
                description: password
              iptype:
                type: str
                description: iptype
              failback_delay:
                type: int
                description: failback delay
              fail_probe_address:
                type: str
                description: probe address
              fail_probe_interval:
                type: int
                description: probe interval
              fail_probe_count:
                type: int
                description: probe count
              fail_probe_threshold:
                type: int
                description: probe threshold
      ethernet_setting:
        type: dict
        description: ethernet configuration
        suboptions:
          link_speed:
            type: str
            description: link speed
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.physifs.physifs import PhysifsArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.physifs.physifs import Physifs


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=PhysifsArgs.argument_spec,
                           supports_check_mode=True)

    result = Physifs(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
