#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for om_pdu
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_users
version_added: 1.0.0
short_description: 'Manages pdu attributes of opengear om pdu'
description: 'Manages pdu attributes of opengear om pdu.'
author: Adrian Van Katwyk
options:
  config:
    description: Retrieve and update pdu information
    type: list
    elements: dict
    suboptions:
      id:
        description: The unique id of the PDU.
        type: str
      name:
        description: A unique user specified name for the PDU.
        type: str
      driver:
        description: The driver to use to control and monitor the PDU.
        type: str
      method:
        description: The method to used to access the PDU, can be 'snmp', 'powerman' or 'shell'.
        type: str
      monitor:
        description: If true the pdu outlets are monitored for any change in status.
        type: bool
      powerman:
        description: The serial specific settings for a PDU.
        type: dict
        suboptions:
          id:
            type: str
          username:
            type: str
          password:
            type: str
          port:
            type: str
      shell:
        description: The serial specific settings for a PDU.
        type: dict
        suboptions:
          id:
            type: str
          username:
            type: str
          passsword:
            type: str
          port:
            type: str
      snmp:
        description: The SNMP configuration to access the PDU.
        type: dict
        suboptions:
          id:
            type: str
          protocol:
            type: str
          address:
            type: str
          port:
            type: int
          version:
            type: str
          community:
            type: str
          auth_protocol:
            type: str
          auth_password:
            type: str
          username:
            type: str
          engine_id:
            type: str
          privacy_protocol:
            type: str
          privacy_password:
            type: str
          security_level:
            type: str
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""
EXAMPLES = """
# Using deleted

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  myos_interfaces:
    operation: deleted

<placeholder for the configuration example after module invocation>


# Using merged

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  nxos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: merged

<placeholder for the configuration example after module invocation>


# Using overridden

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  myos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: overridden

<placeholder for the configuration example after module invocation>


# Using replaced

<placeholder for the configuration example prior to module invocation>

- name: Configure interfaces
  nxos_interfaces:
    config:
      - name: Ethernet1/1
        description: 'Configured by Ansible'
        enable: True
      - name: Ethernet1/2
        description: 'Configured by Ansible'
        enable: False
    operation: replaced

<placeholder for the configuration example after module invocation>


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.pdu.pdu import PduArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.pdu.pdu import Pdu


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=PduArgs.argument_spec,
                           supports_check_mode=True)

    result = Pdu(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
