#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

from __future__ import absolute_import, division, print_function
__metaclass__ = type


ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_static_routes
short_description: Manages static route attributes of opengear om static_routes.
version_added: 1.0.0
description: 
  - Manages static route attributes of opengear om static_routes.
author:
  - "Adrian Van Katwyk (@avankaywk)"
  - "Matt Witmer (@mattwit)"
options:
  config:
    description: Retrieve and update static route information
    type: list
    elements: dict
    id:
      description: Unique id of item.
      type: str
    destination_address:
      description: The destination network/host that the route provides access to.
      type: str
    destination_netmask:
      description: Netmask for IPv4/IPv6 (CIDR format).
      type: int
    gateway_address:
        description: The IPv4/IPv6 address of the router gateway that will route packets to the destination address.
        type: str
    interface:
      description: The network interface to be associated with the route.
    metric:
      description: The route metric, which represents the cost of routing packets via this route. 
      type: int

  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.static_routes.static_routes import StaticRoutesArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.static_routes.static_routes import StaticRoutes


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=StaticRoutesArgs.argument_spec,
                           supports_check_mode=True)

    result = StaticRoutes(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
