#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################


from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'opengear'
}

DOCUMENTATION = """
---
module: om_system
version_added: 1.0.0
short_description: Manages system attributes of om system
description: 
  - Manages system attributes of om system
author: 
  - "Adrian Van Katwyk (@avankatwyk)"
  - "Matt Witmer (@mattwit)"
options:
  config:
    description: The provided configuration
    type: dict
    admin_info:
      type: dict
      description: Update the Operations Manager appliance system information
      suboptions:
        hostname:
          type: str
          description: hostname or address
        contact:
          type: str
          description: contact info
        location:
          type: str
          description: location
    banner:
      type: str
      description: Update the Operations Manager appliance banner text.
    webui_session_timeout:
      type: int
      description: Update the WebUI session timeout (in minutes).
    cli_session_timeout:
      type: int
      description: Update the CLI session timeout (in minutes)
    system_authorized_keys:
      description: Add an SSH key for the specified user
      elements: dict
      suboptions:
        id:
          type: str
          description: The SSH key id to be deleted.
        key:
          type: str
          description: The SSH key
        username:
          type: str
          description: The user associated with the SSH key
    ssh_port:
      type: int
      description: Update the system SSH port
    timezone:
      type: str
      description: Update the system timezone
    time:
      type: str
      description: Update the Operations Manager current time
    cell_reliability_test:
      type: dict
      description: Update configuration items related to running the cell reliability test.
      suboptions:
        enabled:
          type: bool
          description: enabled or disabled
        period:
          type: int
          description: period
        test_url:
          type: list
          elements: str
          description: test usl
        signal_strength_threshold:
          type: dict
          description: signal threshold
          suboptions:
            lower:
              type: int
              description: lower threshold
            upper:
              type: int
              description: upper threshold
    reboot:
      type: bool
      description: reboot
    
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - overridden
    - deleted
    - gathered
    - rendered
    default: merged
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.opengear.om.plugins.module_utils.network.om.argspec.system.system import SystemArgs
from ansible_collections.opengear.om.plugins.module_utils.network.om.config.system.system import System


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=SystemArgs.argument_spec,
                           supports_check_mode=True)

    result = System(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
